// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using prenumerant_api.Models;

#nullable disable

namespace prenumerant_api.Migrations
{
    [DbContext(typeof(SubscribersDbContext))]
    partial class SubscribersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("prenumerant_api.Models.TblSubscriber", b =>
                {
                    b.Property<int>("SubscriberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subscriber_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SubscriberId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delivery_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_nr");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.Property<string>("SocialSecurityNr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("social_security_nr");

                    b.HasKey("SubscriberId")
                        .HasName("tbl_subscribers_pkey");

                    b.ToTable("tbl_subscribers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
