// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using annons_web.Models;

#nullable disable

namespace annons_web.Migrations
{
    [DbContext(typeof(AdsDbContext))]
    [Migration("20260402093441_ChangeNumbersToString")]
    partial class ChangeNumbersToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("annons_web.Models.TblAd", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ad_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdId"));

                    b.Property<int>("AdAdvertiserId")
                        .HasColumnType("integer")
                        .HasColumnName("ad_advertiser_id");

                    b.Property<string>("AdContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad_content");

                    b.Property<decimal>("AdFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ad_fee");

                    b.Property<decimal>("AdPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ad_price");

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad_title");

                    b.HasKey("AdId")
                        .HasName("tbl_ads_pkey");

                    b.HasIndex("AdAdvertiserId");

                    b.ToTable("tbl_ads", (string)null);
                });

            modelBuilder.Entity("annons_web.Models.TblAnnonsorer", b =>
                {
                    b.Property<int>("AdvertiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("advertiser_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("AdvertiserId"));

                    b.Property<int>("AdvertiserType")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("advertiser_type");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CorporateRegNr")
                        .HasColumnType("text")
                        .HasColumnName("corporate_reg_nr");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delivery_address");

                    b.Property<string>("InvoiceAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_nr");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.HasKey("AdvertiserId")
                        .HasName("tbl_annonsorer_pkey");

                    b.ToTable("tbl_annonsorer", (string)null);
                });

            modelBuilder.Entity("annons_web.Models.TblAd", b =>
                {
                    b.HasOne("annons_web.Models.TblAnnonsorer", "AdAdvertiser")
                        .WithMany("TblAds")
                        .HasForeignKey("AdAdvertiserId")
                        .IsRequired()
                        .HasConstraintName("tbl_ads_annonsorer_id_fkey");

                    b.Navigation("AdAdvertiser");
                });

            modelBuilder.Entity("annons_web.Models.TblAnnonsorer", b =>
                {
                    b.Navigation("TblAds");
                });
#pragma warning restore 612, 618
        }
    }
}
